### ISSUE TITLE
Provide explanation to why the lidar does or does not register the ramp as an obstacle

### ISSUE THREAD

**Issue by 1999michael** [UTRA-ART/Caffeine#55]
**Description:**
- Through testing, we have gotten the navigation stack (move base) to go over ramp. This isn't expected as the lidar should register the ramp as a obstacle and try to go around it.

**Goals:**
- [x] Identify whether the lidar registers the ramp as an obstacle
- [x] Be able to explain why it does or does not register the ramp as an obstacle

**Acceptance Criteria:**
- [x] Provide a good explanation for the observation

**Notes:**
- It would be good to change the spawn point to in front of the ramp instead of navigating everytime

**Comment by MarcM0** [comment]
The laser scan detects the ramp as an obstacle (though it also detects the ground when the robot is leaning forwards). It seems that the point cloud can't see it and so its clearing it as an obstacle. As a result, the most of the ramp is not registered as an obstacle most of the time, with exception to the edges. This result also changes based on max and minheight of obstacles, and if the robot is leaning forward. If the point cloud is disabled, leaning forward detects the ramp, however, if the point cloud (and its clearing is on) the ramp is barely registered regardless. 
I changed the range of the laser sensor to 3.3 since that matches the real range of the sensor, and it picks up many more obstacles.
I am currently fine tuning max and min height to maximize seeing real obstacles and minimize seeing the ramp. Also, I'm setting the minheights individually as suggested in issue 47

**Comment by MarcM0** [comment]
I have found some decent max and min values and I've saved them in costmap common param.yaml

**Comment by MarcM0** [comment]
Update: with the new pull requests, the ramp is registered at an obstacle
